In [1]:
import pickle

In [2]:
import pandas as pd

In [3]:
dataset=pd.read_csv("MUL REG& DT.csv")

In [4]:
dataset

ID  AGE  EXPERIENCE  EDUCATION         CITY  SALARY
0   1   25           2  BACHELORS     NEW YORK   45000
1   2   32           5    MASTERS  LOS ANGELES   60000
2   3   28           4  BACHELORS      CHICAGO   52000
3   4   40          10        PhD     NEW YORK   90000
4   5   35           8    MASTERS      CHICAGO   75000
5   6   23           1  BACHELORS  LOS ANGELES   40000
6   7   45          20        PhD     NEW YORK  120000
7   8   38          12    MASTERS      CHICAGO   85000
8   9   30           6  BACHELORS  LOS ANGELES   57000
9  10   29           3    MASTERS     NEW YORK   50000

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [7]:
dataset

ID  AGE  EXPERIENCE  SALARY  EDUCATION_MASTERS  EDUCATION_PhD  \
0   1   25           2   45000              False          False   
1   2   32           5   60000               True          False   
2   3   28           4   52000              False          False   
3   4   40          10   90000              False           True   
4   5   35           8   75000               True          False   
5   6   23           1   40000              False          False   
6   7   45          20  120000              False           True   
7   8   38          12   85000               True          False   
8   9   30           6   57000              False          False   
9  10   29           3   50000               True          False   

   CITY_LOS ANGELES  CITY_NEW YORK  
0             False           True  
1              True          False  
2             False          False  
3             False           True  
4             False          False  
5              True          False  
6             False           True  
7             False          False  
8              True          False  
9             False           True

In [8]:
independant=dataset[['ID', 'AGE', 'EXPERIENCE',
       'EDUCATION_MASTERS', 'EDUCATION_PhD', 
       'CITY_LOS ANGELES', 'CITY_NEW YORK']]
dependant=dataset[['SALARY']]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independant,dependant,test_size=0.20,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [13]:
from sklearn.preprocessing import StandardScaler
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [14]:
preinput=sc.transform([[10,31,5,1,0,1,0]])

C:\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [15]:
preinput

array([[ 1.63678363, -0.33509127, -0.44222778,  1.        , -0.57735027,
         1.73205081, -1.        ]])

In [16]:
import pickle
loaded_model=pickle.load(open("final_preprocessed_model.sav",'rb'))
result=loaded_model.predict(preinput)

In [17]:
result

array([-0.50564161])

In [19]:
preoutput=scy.inverse_transform(result.reshape(-1,1))

In [20]:
preoutput

array([[-0.50564161]])